version: '3.6'
# Made By AndreyKh.
# usage:
# docker-compose build
# docker-compose up


services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    container_name: colman-mongodb
    environment:
      - MONGO_INITDB_DATABASE=colmanEx2
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db: